coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 1%
        informational: false
    patch:
      default:
        target: 85%
        threshold: 1%
        informational: false

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
  hide_project_coverage: false
