name: Create Release
run-name: Creating release

on:
  workflow_dispatch:
  push:
    branches:
      - '**'  # run on all branches
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: python3 -m pip install build tomli --user

      - name: Extract version from pyproject.toml
        id: get-version
        run: |
          VERSION=$(python3 -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['version'])")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build package
        run: python3 -m build

      - name: Determine release tag
        id: release-tag
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ steps.get-version.outputs.version }}-beta-$(date +"%Y-%m-%d-%H-%M-%S")" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${{ steps.release-tag.outputs.tag }}"
          gh release create "$TAG" --repo "${{ github.repository }}" --notes ""
          gh release upload "$TAG" dist/** --repo "${{ github.repository }}"
